# Generated by Django 6.0.4 on 2026-04-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('DEMANDE', 'En attente'), ('PLANIFIE', 'Planifié'), ('CONFIRME', 'Confirmé'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20, verbose_name='Statut'),
        ),
    ]
