# Generated by Django 5.2.12 on 2026-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_teleconsultation',
            field=models.BooleanField(default=False, verbose_name='Téléconsultation'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='teleconsultation_link',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Visio (Jitsi)'),
        ),
    ]
