# Generated by Django 6.0.4 on 2026-05-05 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_rendezvous_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='lien_visio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lien Visioconférence (Salle Jitsi)'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='type_consultation',
            field=models.CharField(choices=[('PRESENTIEL', 'Au cabinet'), ('EN_LIGNE', 'En ligne (Téléconsultation)')], default='PRESENTIEL', max_length=20, verbose_name='Type de consultation'),
        ),
    ]
