# Generated by Django 5.2.14 on 2026-05-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_rendezvous_lien_visio_rendezvous_type_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='est_supprime',
            field=models.BooleanField(default=False, verbose_name='Supprimé'),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='supprime_le',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
    ]
