# Generated by Django 6.0.4 on 2026-05-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='specialite',
            field=models.CharField(blank=True, choices=[('generaliste', 'Médecin Généraliste'), ('cardiologue', 'Cardiologue'), ('dermatologue', 'Dermatologue'), ('gynecologue', 'Gynécologue'), ('pediatre', 'Pédiatre'), ('ophtalmologue', 'Ophtalmologue'), ('dentiste', 'Dentiste'), ('radiologue', 'Radiologue'), ('chirurgien', 'Chirurgien'), ('neurologue', 'Neurologue'), ('pneumologue', 'Pneumologue'), ('rhumatologue', 'Rhumatologue'), ('endocrinologue', 'Endocrinologue'), ('gastro', 'Gastro-entérologue'), ('psy', 'Psychiatre / Psychologue'), ('urgentiste', 'Médecin Urgentiste'), ('autre', 'Autre spécialité')], max_length=30, null=True, verbose_name='Spécialité'),
        ),
    ]
