# Generated by Django 5.2.12 on 2026-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('doctor', 'Médecin'), ('secretary', 'Secrétaire'), ('patient', 'Patient')], default='secretary', max_length=20),
        ),
    ]
