# Generated by Django 6.0.4 on 2026-04-21 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomes', models.TextField(verbose_name='Symptômes observés')),
                ('examen_clinique', models.TextField(blank=True, null=True, verbose_name='Résultats examen clinique')),
                ('diagnostic', models.TextField(blank=True, null=True, verbose_name='Diagnostic retenu')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes du médecin')),
                ('suggestions_ia', models.JSONField(blank=True, help_text="Top 3 pathologies suggérées par l'IA avec scores de confiance", null=True, verbose_name='Suggestions IA')),
                ('ia_utilisee', models.BooleanField(default=False, verbose_name='Module IA utilisé')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('rendez_vous', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation', to='appointments.rendezvous')),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
