# Generated by Django 5.2.12 on 2026-03-07 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(default=list, verbose_name='Symptômes')),
                ('clinical_exam', models.TextField(blank=True, verbose_name='Examen clinique')),
                ('diagnosis', models.CharField(max_length=255, verbose_name='Diagnostic retenu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('ia_suggestions', models.JSONField(blank=True, null=True, verbose_name='Suggestions IA')),
                ('ia_used', models.BooleanField(default=False, verbose_name='IA consultée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='appointments.appointment')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'ordering': ['-created_at'],
            },
        ),
    ]
