# Generated by Django 5.2.15 on 2026-06-24 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_statut_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='telephone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Téléphone'),
        ),
    ]
