# Generated by Django 6.0.4 on 2026-04-21 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_generales', models.TextField(blank=True, null=True, verbose_name='Notes générales')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
                ('medecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LignePrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=200, verbose_name='Médicament')),
                ('dosage', models.CharField(max_length=100, verbose_name='Dosage')),
                ('unite', models.CharField(choices=[('comprime', 'Comprimé'), ('gelule', 'Gélule'), ('sachet', 'Sachet'), ('ampoule', 'Ampoule'), ('sirop', 'Sirop (ml)'), ('gouttes', 'Gouttes'), ('creme', 'Crème'), ('autre', 'Autre')], default='comprime', max_length=20, verbose_name='Unité')),
                ('frequence', models.CharField(max_length=100, verbose_name='Fréquence')),
                ('duree', models.CharField(max_length=100, verbose_name='Durée')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions particulières')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='prescriptions.prescription')),
            ],
            options={
                'verbose_name': 'Ligne de prescription',
                'verbose_name_plural': 'Lignes de prescription',
            },
        ),
    ]
